name: Jekyllstrap
url: http://ogaclejapan.github.io
baseurl: /jekyllstrap
timezone: Asia/Tokyo
encoding: utf-8

markdown: redcarpet
pygments: true
permalink: pretty
paginate: 10

owner : 
  name : ogaclejapan
  github : ogaclejapan
  twitter : ogaclejapan

#google_analytics :
#  tracking_id : 'UA-XXXXXXXX-X'

#addthis:
#  pub_id: 'ra-XXXXXXXXXXXXXXX'

exclude: ["README.md", "LICENSE", ".gitignore"]
