# Change your site name, url, etc.
name: Jekyllstrap
url: http://ogaclejapan.github.io
baseurl: /jekyllstrap
timezone: Asia/Tokyo
encoding: utf-8

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "tables", "fenced_code_blocks"]

pygments: true
permalink: pretty
paginate: 5

# Change your name, GitHub name, Twitter id, etc.
owner : 
  name : ogaclejapan
  github : ogaclejapan
  twitter : ogaclejapan
#  googleplus : 
#  facebook : 

# See http://schema.org/Article
schema_article_type : Article

#google_analytics :
#  tracking_id : 'UA-XXXXXXXX-X'

#addthis:
#  pub_id: 'ra-XXXXXXXXXXXXXXX'

exclude: ["README.md", "LICENSE", ".gitignore", "s3_website.yml"]
